# events is required, but defaults are ok
events { }

# A http server, listening at port 80 (inside its own container)
http {
  server {
    listen 80;

    # Requests starting with root (/) are handled as follows
    location / {
      # The following 3 lines are required for Vite's hot reload mechanism to work through the proxy
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';

      # Requests are directed to http://app:5173  (use app, not localhost!)
      proxy_pass http://app:5173;
    }
  }
}
